log:
  handlers:
    default: "default"
  providers:
    default:
      - format: "console"
        level: "info"
        verbosity: 3
        output:
          stdout:
            enable: true
          stderr:
            enable: false
          file:
            enable: false
            path: "/var/log/opencode-connect/opencode-connect.log"
            maxSize: "10mb"
            maxAge: "7d"
            maxBackups: 10
            compress: true

plugins:
  chatapi:
    enabled: true
    listen: ":8192"

opencode:
  baseurl: "http://127.0.0.1:4096"
  username: ""
  password: ""
